#!/usr/bin/env bash

emacs_theme=ewal-doom-one

reload_themes() {

    # If active tmux session, reload
    if (tmux list-sessions &>/dev/null); then
        tmux source-file $HOME/.tmux.conf
        echo "Reloaded tmux"
    fi

    # If i3status template is installed
    if [[ -n `which i3 2>/dev/null` && -f $HOME/.cache/wal/i3status.conf ]]; then
        mkdir -p $HOME/.config/i3status
        cp -r $HOME/.cache/wal/i3status.conf $HOME/.config/i3status/config
        i3 reload &>/dev/null
        echo "Reloaded i3status.conf"
    fi

    # If emacs daemon is running, reload theme
    if (ps -ef | grep emacs | grep daemon &>/dev/null); then
        emacsclient -e "(load-theme '$emacs_theme)" &>/dev/null
        echo "Reloaded emacs theme ($emacs_theme)"
    fi
}

args=$@
[[ !($1 =~ $-) && -e $1 ]] && args="-i $@"

(wal -n $args || wal $args) && reload_themes

if [[ -f $HOME/.cache/wal/set_nitrogen.sh ]]; then
    chmod a+x $HOME/.cache/wal/set_nitrogen.sh
    ($HOME/.cache/wal/set_nitrogen.sh &)
fi

if [[ -f $HOME/.config/wal/wal-set-post ]]; then
    emacs_theme=$emacs_theme $HOME/.config/wal/wal-set-post || true
fi

if [[ `pywalfox --help &>/dev/null` ]]; then
    pywalfox update
fi
