#!/bin/bash

emacs_theme=ewal-doom-one

source $HOME/.profile

reload_themes() {

    # If active tmux session, reload
    if (tmux list-sessions &>/dev/null); then
        tmux source-file $HOME/.tmux.conf
        echo "Reloaded tmux"
    fi

    # If active tmux session, reload
    if (wemux list-sessions &>/dev/null); then
        wemux source-file $HOME/.tmux.conf
        echo "Reloaded wemux"
    fi

    # If i3status template is installed
    if [[ `command -v i3` ]]; then
        i3 reload &>/dev/null
        echo "Reloaded i3"
    fi

    # if [[ -e $HOME/.config/polybar/launch.sh ]]; then
    #     $HOME/.config/polybar/launch.sh
    # fi

    # If emacs daemon is running, reload theme
    if (ps -ef | grep emacs | grep daemon &>/dev/null); then
        emacsclient -e "(load-theme '$emacs_theme)" &>/dev/null
        echo "Reloaded emacs theme ($emacs_theme)"
    fi
}

args=$@
[[ !($1 =~ $-) && -e $1 ]] && args="-i $@"

echo "wal $args"

(wal -n $args || wal $args) && reload_themes

if [[ -f $HOME/.cache/wal/set_nitrogen.sh ]]; then
    chmod a+x $HOME/.cache/wal/set_nitrogen.sh
    ($HOME/.cache/wal/set_nitrogen.sh &)
fi

if [[ -f $HOME/.config/wal/wal-set-post ]]; then
    emacs_theme=$emacs_theme $HOME/.config/wal/wal-set-post || true
fi

if [[ `command -v pywalfox` ]]; then
    pywalfox update 2>/dev/null || true
fi
